version: '3.8'

services:
  web:
    build: .
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
      - ./docker/vhost.conf:/etc/apache2/sites-available/000-default.conf
    depends_on:
      - db
      - mongo

  db:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: EcoRide
      MYSQL_USER: ecoride_user
      MYSQL_PASSWORD: ecoride_pass
    volumes:
      - db_data:/var/lib/mysql
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d

  mongo:
    image: mongo:6
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - "8081:80"
    environment:
      PMA_HOST: db
      PMA_USER: ecoride_user
      PMA_PASSWORD: ecoride_pass
    depends_on:
      - db

volumes:
  db_data:
  mongo-data:
